// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: backend2.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend2_SimpleCall_FullMethodName  = "/protobuf.Backend2/SimpleCall"
	Backend2_SimpleCall2_FullMethodName = "/protobuf.Backend2/SimpleCall2"
)

// Backend2Client is the client API for Backend2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Backend2Client interface {
	SimpleCall(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error)
	SimpleCall2(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error)
}

type backend2Client struct {
	cc grpc.ClientConnInterface
}

func NewBackend2Client(cc grpc.ClientConnInterface) Backend2Client {
	return &backend2Client{cc}
}

func (c *backend2Client) SimpleCall(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, Backend2_SimpleCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backend2Client) SimpleCall2(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, Backend2_SimpleCall2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Backend2Server is the server API for Backend2 service.
// All implementations must embed UnimplementedBackend2Server
// for forward compatibility
type Backend2Server interface {
	SimpleCall(context.Context, *Arg) (*Resp, error)
	SimpleCall2(context.Context, *Arg) (*Resp, error)
	mustEmbedUnimplementedBackend2Server()
}

// UnimplementedBackend2Server must be embedded to have forward compatible implementations.
type UnimplementedBackend2Server struct {
}

func (UnimplementedBackend2Server) SimpleCall(context.Context, *Arg) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleCall not implemented")
}
func (UnimplementedBackend2Server) SimpleCall2(context.Context, *Arg) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleCall2 not implemented")
}
func (UnimplementedBackend2Server) mustEmbedUnimplementedBackend2Server() {}

// UnsafeBackend2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Backend2Server will
// result in compilation errors.
type UnsafeBackend2Server interface {
	mustEmbedUnimplementedBackend2Server()
}

func RegisterBackend2Server(s grpc.ServiceRegistrar, srv Backend2Server) {
	s.RegisterService(&Backend2_ServiceDesc, srv)
}

func _Backend2_SimpleCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Backend2Server).SimpleCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend2_SimpleCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Backend2Server).SimpleCall(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend2_SimpleCall2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Backend2Server).SimpleCall2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend2_SimpleCall2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Backend2Server).SimpleCall2(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend2_ServiceDesc is the grpc.ServiceDesc for Backend2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Backend2",
	HandlerType: (*Backend2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleCall",
			Handler:    _Backend2_SimpleCall_Handler,
		},
		{
			MethodName: "SimpleCall2",
			Handler:    _Backend2_SimpleCall2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend2.proto",
}
