// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: test/protobuf/backend3.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend3_SimpleCall_FullMethodName = "/protobuf.Backend3/SimpleCall"
)

// Backend3Client is the client API for Backend3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Backend3Client interface {
	SimpleCall(ctx context.Context, in *Arg3, opts ...grpc.CallOption) (*Resp3, error)
}

type backend3Client struct {
	cc grpc.ClientConnInterface
}

func NewBackend3Client(cc grpc.ClientConnInterface) Backend3Client {
	return &backend3Client{cc}
}

func (c *backend3Client) SimpleCall(ctx context.Context, in *Arg3, opts ...grpc.CallOption) (*Resp3, error) {
	out := new(Resp3)
	err := c.cc.Invoke(ctx, Backend3_SimpleCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Backend3Server is the server API for Backend3 service.
// All implementations must embed UnimplementedBackend3Server
// for forward compatibility
type Backend3Server interface {
	SimpleCall(context.Context, *Arg3) (*Resp3, error)
	mustEmbedUnimplementedBackend3Server()
}

// UnimplementedBackend3Server must be embedded to have forward compatible implementations.
type UnimplementedBackend3Server struct {
}

func (UnimplementedBackend3Server) SimpleCall(context.Context, *Arg3) (*Resp3, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleCall not implemented")
}
func (UnimplementedBackend3Server) mustEmbedUnimplementedBackend3Server() {}

// UnsafeBackend3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Backend3Server will
// result in compilation errors.
type UnsafeBackend3Server interface {
	mustEmbedUnimplementedBackend3Server()
}

func RegisterBackend3Server(s grpc.ServiceRegistrar, srv Backend3Server) {
	s.RegisterService(&Backend3_ServiceDesc, srv)
}

func _Backend3_SimpleCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Backend3Server).SimpleCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend3_SimpleCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Backend3Server).SimpleCall(ctx, req.(*Arg3))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend3_ServiceDesc is the grpc.ServiceDesc for Backend3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Backend3",
	HandlerType: (*Backend3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleCall",
			Handler:    _Backend3_SimpleCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/protobuf/backend3.proto",
}
