// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.30.2
// source: test/protobuf/backend3.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Arg3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Arg3) Reset() {
	*x = Arg3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_protobuf_backend3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg3) ProtoMessage() {}

func (x *Arg3) ProtoReflect() protoreflect.Message {
	mi := &file_test_protobuf_backend3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg3.ProtoReflect.Descriptor instead.
func (*Arg3) Descriptor() ([]byte, []int) {
	return file_test_protobuf_backend3_proto_rawDescGZIP(), []int{0}
}

func (x *Arg3) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Resp3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Resp3) Reset() {
	*x = Resp3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_protobuf_backend3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp3) ProtoMessage() {}

func (x *Resp3) ProtoReflect() protoreflect.Message {
	mi := &file_test_protobuf_backend3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp3.ProtoReflect.Descriptor instead.
func (*Resp3) Descriptor() ([]byte, []int) {
	return file_test_protobuf_backend3_proto_rawDescGZIP(), []int{1}
}

func (x *Resp3) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_test_protobuf_backend3_proto protoreflect.FileDescriptor

var file_test_protobuf_backend3_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x1a, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x33,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x70, 0x33, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x39, 0x0a, 0x08, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x33, 0x12, 0x2d, 0x0a,
	0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x72, 0x67, 0x33, 0x1a, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x33, 0x42, 0x0f, 0x5a, 0x0d,
	0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_protobuf_backend3_proto_rawDescOnce sync.Once
	file_test_protobuf_backend3_proto_rawDescData = file_test_protobuf_backend3_proto_rawDesc
)

func file_test_protobuf_backend3_proto_rawDescGZIP() []byte {
	file_test_protobuf_backend3_proto_rawDescOnce.Do(func() {
		file_test_protobuf_backend3_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_protobuf_backend3_proto_rawDescData)
	})
	return file_test_protobuf_backend3_proto_rawDescData
}

var file_test_protobuf_backend3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_protobuf_backend3_proto_goTypes = []interface{}{
	(*Arg3)(nil),  // 0: protobuf.Arg3
	(*Resp3)(nil), // 1: protobuf.Resp3
}
var file_test_protobuf_backend3_proto_depIdxs = []int32{
	0, // 0: protobuf.Backend3.SimpleCall:input_type -> protobuf.Arg3
	1, // 1: protobuf.Backend3.SimpleCall:output_type -> protobuf.Resp3
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_protobuf_backend3_proto_init() }
func file_test_protobuf_backend3_proto_init() {
	if File_test_protobuf_backend3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_protobuf_backend3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_protobuf_backend3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_protobuf_backend3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_protobuf_backend3_proto_goTypes,
		DependencyIndexes: file_test_protobuf_backend3_proto_depIdxs,
		MessageInfos:      file_test_protobuf_backend3_proto_msgTypes,
	}.Build()
	File_test_protobuf_backend3_proto = out.File
	file_test_protobuf_backend3_proto_rawDesc = nil
	file_test_protobuf_backend3_proto_goTypes = nil
	file_test_protobuf_backend3_proto_depIdxs = nil
}
