// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: backend1.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend1_SimpleCall_FullMethodName  = "/protobuf.Backend1/SimpleCall"
	Backend1_SimpleCall2_FullMethodName = "/protobuf.Backend1/SimpleCall2"
)

// Backend1Client is the client API for Backend1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Backend1Client interface {
	SimpleCall(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error)
	SimpleCall2(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error)
}

type backend1Client struct {
	cc grpc.ClientConnInterface
}

func NewBackend1Client(cc grpc.ClientConnInterface) Backend1Client {
	return &backend1Client{cc}
}

func (c *backend1Client) SimpleCall(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, Backend1_SimpleCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backend1Client) SimpleCall2(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, Backend1_SimpleCall2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Backend1Server is the server API for Backend1 service.
// All implementations must embed UnimplementedBackend1Server
// for forward compatibility
type Backend1Server interface {
	SimpleCall(context.Context, *Arg) (*Resp, error)
	SimpleCall2(context.Context, *Arg) (*Resp, error)
	mustEmbedUnimplementedBackend1Server()
}

// UnimplementedBackend1Server must be embedded to have forward compatible implementations.
type UnimplementedBackend1Server struct {
}

func (UnimplementedBackend1Server) SimpleCall(context.Context, *Arg) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleCall not implemented")
}
func (UnimplementedBackend1Server) SimpleCall2(context.Context, *Arg) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleCall2 not implemented")
}
func (UnimplementedBackend1Server) mustEmbedUnimplementedBackend1Server() {}

// UnsafeBackend1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Backend1Server will
// result in compilation errors.
type UnsafeBackend1Server interface {
	mustEmbedUnimplementedBackend1Server()
}

func RegisterBackend1Server(s grpc.ServiceRegistrar, srv Backend1Server) {
	s.RegisterService(&Backend1_ServiceDesc, srv)
}

func _Backend1_SimpleCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Backend1Server).SimpleCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend1_SimpleCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Backend1Server).SimpleCall(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend1_SimpleCall2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Backend1Server).SimpleCall2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend1_SimpleCall2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Backend1Server).SimpleCall2(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend1_ServiceDesc is the grpc.ServiceDesc for Backend1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Backend1",
	HandlerType: (*Backend1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleCall",
			Handler:    _Backend1_SimpleCall_Handler,
		},
		{
			MethodName: "SimpleCall2",
			Handler:    _Backend1_SimpleCall2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend1.proto",
}
